#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v10
# autospec commit: 5905be9
#
Name     : perl-Devel-Size
Version  : 0.84
Release  : 28
URL      : https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/Devel-Size-0.84.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/Devel-Size-0.84.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Devel-Size-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=pod
Devel::Size - Perl extension for finding the memory usage of Perl variables

%package dev
Summary: dev components for the perl-Devel-Size package.
Group: Development
Provides: perl-Devel-Size-devel = %{version}-%{release}
Requires: perl-Devel-Size = %{version}-%{release}

%description dev
dev components for the perl-Devel-Size package.


%package perl
Summary: perl components for the perl-Devel-Size package.
Group: Default
Requires: perl-Devel-Size = %{version}-%{release}

%description perl
perl components for the perl-Devel-Size package.


%prep
%setup -q -n Devel-Size-0.84
cd %{_builddir}/Devel-Size-0.84
pushd ..
cp -a Devel-Size-0.84 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Devel::Size.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
